Replaces ShadowSpannedString with ShadowSpannableString
Due to an unresolved conflict in the ShadowWrangler only one of these two shadows classes can be bound. Binding both ShadowSpannedString and ShadowSpannableString results in one calling through to real android classes, which results in the following exception:

java.lang.RuntimeException: java.lang.IllegalAccessException: Class com.xtremelabs.robolectric.bytecode.ShadowWrangler can not access a member of class android.text.SpannableStringInternal with modifiers "public"
	at com.xtremelabs.robolectric.bytecode.ShadowWrangler.readField(ShadowWrangler.java:257)
	at com.xtremelabs.robolectric.bytecode.ShadowWrangler.shadowFor(ShadowWrangler.java:158)
	at com.xtremelabs.robolectric.bytecode.ShadowWrangler$InvocationPlan.prepare(ShadowWrangler.java:340)
	at com.xtremelabs.robolectric.bytecode.ShadowWrangler.methodInvoked(ShadowWrangler.java:88)
	at com.xtremelabs.robolectric.bytecode.RobolectricInternals.methodInvoked(RobolectricInternals.java:111)
	at android.text.SpannedString.<init>(SpannedString.java)
	...
Caused by: java.lang.IllegalAccessException: Class com.xtremelabs.robolectric.bytecode.ShadowWrangler can not access a member of class android.text.SpannableStringInternal with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:65)
	at java.lang.reflect.Field.doSecurityCheck(Field.java:960)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:896)
	at java.lang.reflect.Field.get(Field.java:358)
	at com.xtremelabs.robolectric.bytecode.ShadowWrangler.readField(ShadowWrangler.java:255)
	... 34 more